[package]
name = "http_server_template"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
env_logger = "0.11.3"
log = "0.4.21"
serde_json = "1.0.114"
tiny_http = "0.12"
tungstenite = { version = "0.21", features = ["native-tls"] }
